/**
 * Frontend-owned domain vocabulary for the personal review experience.
 *
 * These models deliberately describe what the interface needs instead of
 * mirroring the current Python payloads. A small translator in the data layer
 * (often called an adapter) can convert mock, FastAPI, or Go responses into
 * these stable types before the UI receives them.
 */

/** Stable identifiers used for navigation, filtering, and data-source lookups. */
export type AreaId =
  | "mail"
  | "home"
  | "health"
  | "reading"
  | "meals"
  | "thoughtful"
  | "money";

/** The intentionally small set of open/done states currently shown by the Review screen. */
export type EntryState = "open" | "done";

/** User-selectable queue views. `all` includes both open and completed work. */
export type QueueFilter = "open" | "all" | "done";

/** Restrained palette roles that visually distinguish areas without encoding status alone. */
export type Accent = "juniper" | "iris" | "saffron" | "rose";

/** A compact label/value pair rendered beneath an entry's primary explanation. */
export interface EntryMetadata {
  /** Short utility label such as "Due", "From", or "Category". */
  label: string;
  /** Human-readable value associated with the label. */
  value: string;
  /** Adds a visual attention marker while preserving the text label as the semantic signal. */
  attention?: boolean;
}

/** A single actionable or completed piece of personal work. */
export interface ReviewEntry {
  /** Stable identity used when updating one entry without relying on display text. */
  id: string;
  /** Scannable action-oriented summary shown as the row heading. */
  title: string;
  /** Optional long-form context; the UI must preserve wrapping and remain readable. */
  details?: string;
  /** Optional source or destination opened in a separate browser tab. */
  href?: string;
  /** Current completion state controlled by the row's checkbox-style button. */
  state: EntryState;
  /** Secondary details kept explicit instead of accepting arbitrary backend fields in components. */
  metadata: EntryMetadata[];
}

/**
 * One generated idea displayed in the Thoughtful Suggestions area's
 * "This Week" section.
 *
 * These ideas intentionally do not use `ReviewEntry`: browsing an idea or
 * saving it as a Favorite is not the same as completing a task. Keeping the
 * shapes separate prevents the Review screen from adding checkboxes, open/done
 * filters, or cleared counts to small gestures for the user's wife.
 */
export interface ThoughtfulSuggestion {
  /** Stable source identity used when the empty heart sends a Favorite PUT. */
  id: string;
  /** Short gesture shown as the suggestion heading. */
  title: string;
  /** Concrete context that makes the gesture easy to act on this week. */
  details: string;
  /** Searchable grouping such as care, encouragement, or quality time. */
  category: string;
}

/**
 * A durable copy shown in the Thoughtful Suggestions area's Favorites section.
 *
 * `id` identifies the saved record and is used by DELETE. The separate
 * `sourceSuggestionId` points back to the weekly idea that was favorited. When
 * that source is still present in This Week, the interface can match these two
 * fields and render its heart as filled without relying on duplicated prose.
 */
export interface ThoughtfulFavorite {
  /** Durable Favorite identity generated by the server. */
  id: string;
  /** Identity of the weekly suggestion from which this Favorite was copied. */
  sourceSuggestionId: string;
  /** Saved heading retained even after a later weekly refresh replaces the source. */
  title: string;
  /** Saved gesture details retained independently of the weekly list. */
  details: string;
  /** Saved category used by the Review screen's text search. */
  category: string;
  /** New York-local YYYY-MM-DD date on which the Favorite was created. */
  savedAt: string;
}

/**
 * The complete specialized content rendered inside the Thoughtful Suggestions
 * area.
 *
 * A weekly refresh replaces `suggestions` and `weekStarting` but preserves
 * `favorites`. The database revision travels with the same snapshot because a
 * heart mutation must send the exact version it is changing; Go rejects a stale
 * version instead of overwriting a simultaneous refresh or another heart click.
 */
export interface ThoughtfulSuggestionsContent {
  /** Sunday beginning the generated suggestion week, formatted YYYY-MM-DD. */
  weekStarting: string;
  /** Exactly five current-week ideas in their generated display order. */
  suggestions: ThoughtfulSuggestion[];
  /** Durable saved ideas, ordered newest first by the backend. */
  favorites: ThoughtfulFavorite[];
  /** Positive database version required by add/remove Favorite requests. */
  revision: number;
}

/**
 * One top-level group on the Review screen, such as Mail, Home, or Health.
 *
 * The component renders each `ReviewArea` as one `<section>` with the CSS class
 * `.area-section`. In that sense, the domain object supplies the data for the
 * visible area section, but it is not a CSS class or React component itself.
 *
 * The current mock keeps entries directly inside an area. If Mail later needs
 * smaller groups such as "Needs attention" and "Waiting on", those would become
 * a separate `ReviewSection` model nested inside this `ReviewArea`.
 */
export interface ReviewArea {
  /** Stable identifier shared by navigation and entry mutation calls. */
  id: AreaId;
  /** User-facing name; avoids exposing implementation language such as "loop". */
  name: string;
  /** One-sentence explanation of why this area appears in the review queue. */
  description: string;
  /** Visual role used by icons and the cadence rail. */
  accent: Accent;
  /**
   * Task-like entries currently known to the frontend data source.
   * Thoughtful Suggestions leaves this empty because its ideas have no done state.
   */
  entries: ReviewEntry[];
  /**
   * Specialized browse-and-save content present only on the Thoughtful
   * Suggestions area. Other areas omit it and continue rendering `entries`.
   */
  thoughtfulSuggestions?: ThoughtfulSuggestionsContent;
}
